# /espace-perso

app_account :
    path:     /
    defaults:
        _controller: TrailWarehouseAppBundle:Account:index

app_account_remove_address :
    path:     /supprimer-adresse
    defaults:
        _controller: TrailWarehouseAppBundle:Account:removeAddress
