app_user_account:
    path:     /espace-perso
    defaults:
        _controller: TrailWarehouseAppBundle:User:account

app_user_signup:
    path:     /inscription
    defaults:
        _controller: TrailWarehouseAppBundle:User:signup

app_user_signin:
    path:     /connexion
    defaults:
        _controller: TrailWarehouseAppBundle:User:signin

app_user_signin_check:
    path:     /verification

app_user_signout:
    path:     /deconnexion
