app_api_brand_get_all :
    path                 : /
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Brand:getAll

app_api_brand_get     :
    path                 : /{id}
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Brand:get
    requirements         :
        id               : '\d+'

app_api_brand_add     :
    path                 : /
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Brand:add

app_api_brand_modify  :
    path                 : /{id}
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Brand:modify
    requirements         :
        id               : '\d+'

app_api_brand_remove  :
    path                 : /{id}
    methods              : [DELETE]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Brand:remove
    requirements         :
        id               : '\d+'
