app_api_product_get_all :
    path                : /
    methods             : [GET]
    defaults            :
        _controller     : TrailWarehouseAppBundle:Api/Product:getAll

app_api_product_get_by  :
    path                : /family-{family}/color-{color}/size-{size}
    methods             : [GET]
    defaults            :
        _controller     : TrailWarehouseAppBundle:Api/Product:getBy
        color           : 1
        size            : 1
    requirements        :
        family          : '\d+'
        color           : '\d+'
        size            : '\d+'

app_api_product_get     :
    path                : /{id}
    methods             : [GET]
    defaults            :
        _controller     : TrailWarehouseAppBundle:Api/Product:get
    requirements        :
        id              : '\d+'

app_api_product_add     :
    path                : /
    methods             : [POST]
    defaults            :
        _controller     : TrailWarehouseAppBundle:Api/Product:add

app_api_product_modify  :
    path                : /{id}
    methods             : [POST]
    defaults            :
        _controller     : TrailWarehouseAppBundle:Api/Product:modify
    requirements        :
        id              : '\d+'

app_api_product_remove  :
    path                : /{id}
    methods             : [DELETE]
    defaults            :
        _controller     : TrailWarehouseAppBundle:Api/Product:remove
    requirements        :
        id              : '\d+'
