app_api_coordinate_get_all :
    path                 : /
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Coordinate:getAll

app_api_coordinate_get     :
    path                 : /{id}
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Coordinate:get
    requirements         :
        id               : '\d+'

app_api_coordinate_add     :
    path                 : /
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Coordinate:add

app_api_coordinate_modify  :
    path                 : /{id}
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Coordinate:modify
    requirements         :
        id               : '\d+'

app_api_coordinate_remove  :
    path                 : /{id}
    methods              : [DELETE]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Coordinate:remove
    requirements         :
        id               : '\d+'
