app_api_category_get_all:
    path            : /
    methods         : [GET]
    defaults        :
        _controller : TrailWarehouseAppBundle:Api/Category:getAll

app_api_category_get:
    path            : /{id}
    methods         : [GET]
    defaults        :
        _controller : TrailWarehouseAppBundle:Api/Category:get
    requirements    :
        id          : '\d+'

app_api_category_add:
    path            : /
    methods         : [POST]
    defaults        :
        _controller : TrailWarehouseAppBundle:Api/Category:add

app_api_category_modify:
    path            : /{id}
    methods         : [POST]
    defaults        :
        _controller : TrailWarehouseAppBundle:Api/Category:modify
    requirements    :
        id          : '\d+'

app_api_category_remove:
    path            : /{id}
    methods         : [DELETE]
    defaults        :
        _controller : TrailWarehouseAppBundle:Api/Category:remove
    requirements    :
        id          : '\d+'
