app_api_promo_get_all :
    path                 : /
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Promo:getAll

app_api_promo_get     :
    path                 : /{id}
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Promo:get
    requirements         :
        id               : '\d+'

app_api_promo_add     :
    path                 : /
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Promo:add

app_api_promo_modify  :
    path                 : /{id}
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Promo:modify
    requirements         :
        id               : '\d+'

app_api_promo_remove  :
    path                 : /{id}
    methods              : [DELETE]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Promo:remove
    requirements         :
        id               : '\d+'
