app_api_color_get_all :
    path                 : /
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Color:getAll

app_api_color_get     :
    path                 : /{id}
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Color:get
    requirements         :
        id               : '\d+'

app_api_color_add     :
    path                 : /
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Color:add

app_api_color_modify  :
    path                 : /{id}
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Color:modify
    requirements         :
        id               : '\d+'

app_api_color_remove  :
    path                 : /{id}
    methods              : [DELETE]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Color:remove
    requirements         :
        id               : '\d+'
