app_api_address_get_all :
    path                 : /
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Address:getAll

app_api_address_get     :
    path                 : /{id}
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Address:get
    requirements         :
        id               : '\d+'

app_api_address_add     :
    path                 : /
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Address:add

app_api_address_modify  :
    path                 : /{id}
    methods              : [POST]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Address:modify
    requirements         :
        id               : '\d+'

app_api_address_remove  :
    path                 : /{id}
    methods              : [DELETE]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Api/Address:remove
    requirements         :
        id               : '\d+'
