app_api_category_root :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_category.yml"
    prefix            : /categories

app_api_brand_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_brand.yml"
    prefix            : /brands

app_api_family_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_family.yml"
    prefix            : /families

app_api_size_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_size.yml"
    prefix            : /sizes

app_api_color_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_color.yml"
    prefix            : /colors

app_api_product_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_product.yml"
    prefix            : /products

app_api_rate_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_rate.yml"
    prefix            : /rates

app_api_rating_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_rating.yml"
    prefix            : /ratings

app_api_order_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_order.yml"
    prefix            : /orders

app_api_promo_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_promo.yml"
    prefix            : /promos

app_api_member_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_member.yml"
    prefix            : /members

app_api_coordinate_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_coordinate.yml"
    prefix            : /coordinates

app_api_stat_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_stat.yml"
    prefix            : /stats

app_api_test_root   :
    resource          : "@TrailWarehouseAppBundle/Resources/config/Api/routing_test.yml"
    prefix            : /tests
