app_api_product_get_all       :
    path                      : /
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getAll

app_api_product_get_by        :
    path                      : /family/{family}/color/{color}/size/{size}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getBy
    requirements              :
        family                : '\d+'
        color                 : '\d+'
        size                  : '\d+'

app_api_product_get_by_family :
    path                      : /family/{family}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getByFamily
    requirements              :
        family                : '\d+'
        color                 : '\d+'

app_api_product_get_by_color  :
    path                      : /family/{family}/color/{color}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getByColor
    requirements              :
        family                : '\d+'
        color                 : '\d+'

app_api_product_get_by_size   :
    path                      : /family/{family}/size/{size}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getBySize
    requirements              :
        family                : '\d+'
        color                 : '\d+'
        size                  : '\d+'

app_api_product_get           :
    path                      : /{id}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:get
    requirements              :
        id                    : '\d+'

app_api_product_get_best      :
    path                      : /best/{family_id}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getBest
    requirements              :
        id                    : '\d+'

app_api_product_get_random    :
    path                      : /random
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getOneRand

app_api_product_get_randoms   :
    path                      : /random/{count}
    methods                   : [GET]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:getRand
        count                 : 5
    requirements              :
        id                    : '\d+'

app_api_product_add           :
    path                      : /
    methods                   : [POST]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:add

app_api_product_modify        :
    path                      : /{id}
    methods                   : [POST]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:modify
    requirements              :
        id                    : '\d+'

app_api_product_remove        :
    path                      : /{id}
    methods                   : [DELETE]
    defaults                  :
        _controller           : TrailWarehouseAppBundle:Api/Product:remove
    requirements              :
        id               : '\d+'
