app_shop             :
    path             : /
    defaults         :
        _controller  : TrailWarehouseAppBundle:Shop:index
    requirements     :
        url          : .*/$

app_shop_categories  :
    path             : /toutes-categories
    defaults         :
        _controller  : TrailWarehouseAppBundle:Shop:categories

app_shop_category    :
    path             : /categorie-{slug}
    defaults         :
        _controller  : TrailWarehouseAppBundle:Shop:category

app_shop_family      :
    path             : /fiche-produit/{slug}
    defaults         :
        _controller  : TrailWarehouseAppBundle:Shop:family

app_shop_add_to_cart :
    path             : /cart/add
    methods          : [POST]
    defaults         :
        _controller  : TrailWarehouseAppBundle:Shop:addToCart
