<?php

namespace TrailWarehouse\AppBundle\Repository;
use TrailWarehouse\AppBundle\Entity\Address;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends CommonRepository
{
    /**
     * Check if a user has already set an address with this title
     * @param  Address $address User's Address
     * @return boolean
     */
    public function isDoublon(Address $address): boolean
    {
        $address = $this->createQueryBuilder($this->entity_name)
            ->andWhere($this->entity_name.'.user = :user')
            ->setParameter('user', $address->getUser())
            ->andWhere($this->entity_name.'.title = :title')
            ->setParameter('title', $address->getTitle())
            ->getQuery()
            ->getArrayResult()
        ;
        return !empty($address);
    }
}
