<?php

namespace TrailWarehouse\AppBundle\Repository;
use TrailWarehouse\AppBundle\Repository\CommonRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends CommonRepository
{
  public function isDoublon($address) {
    $address = $this->createQueryBuilder($this->entity_name)
      ->andWhere($this->entity_name.'.user = :user')
      ->setParameter('user', $address->getUser())
      ->andWhere($this->entity_name.'.title = :title')
      ->setParameter('title', $address->getTitle())
      ->getQuery()
      ->getArrayResult()
    ;
    return !empty($address);
  }
}
