<?php

namespace TrailWarehouse\AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends CommonRepository
{
  public function getOneBy($field, $value) {
    return $this->createQueryBuilder('category')
      ->where('category.'.$field.' = :value')
      ->setParameter('value', $value)
      ->getQuery()
      ->getOneOrNullResult()
    ;
  }

  public function get($id) {
    return $this->getOneBy('id', $id);
  }

  public function getAll() {
    $builder = $this->_em->createQueryBuilder();
    $builder
      ->select('category')
      ->from($this->_entityName, 'category')
      ->getQuery()
      ->getArrayResult()
    ;
    dump($builder->getQuery());
  }
}
