<?php

namespace TrailWarehouse\AppBundle\Repository;
use TrailWarehouse\AppBundle\Repository\CommonRepository;

/**
 * CoordinateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinateRepository extends CommonRepository
{
  public function isDoublon($coordinate) {
    $coordinates = $this->createQueryBuilder('coordinate')
      ->andWhere('coordinate.user = :user')
      ->setParameter('user', $coordinate->getUser())
      ->andWhere('coordinate.title = :title')
      ->setParameter('title', $coordinate->getTitle())
      ->getQuery()
      ->getArrayResult()
    ;
    return !empty($coordinates);
  }
}
