<?php

namespace TrailWarehouse\AppBundle\Repository;
use TrailWarehouse\AppBundle\Repository\CommonRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends CommonRepository
{
  protected function getBuilder()
  {
    return $this->createQueryBuilder('tw_order')
      ->innerJoin('tw_order.user', 'user')
      ->leftJoin('tw_order.address', 'address')
    ;
  }
}
