<?php

namespace TrailWarehouse\AppBundle\Repository;

/**
 * OrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductRepository extends CommonRepository
{
  protected function getBuilder()
  {
    return $this->createQueryBuilder($this->entity_name)
      ->addSelect('product')
      ->innerJoin($this->entity_name.'.product', 'product')
    ;
  }
}
