<?php

namespace TrailWarehouse\AppBundle\Repository;

/**
 * VATRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
}
