<?php

namespace TrailWarehouse\AppBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends CommonRepository implements UserLoaderInterface
{
  public function loadUserByUsername($email)
   {
      return $this->createQueryBuilder('u')
        ->where('u.email = :email')
        ->setParameter('email', $email)
        ->getQuery()
        ->getOneOrNullResult()
      ;
  }
}
