<?php

namespace TrailWarehouse\AppBundle\Repository;

/**
 * VatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VatRepository extends CommonRepository
{
}
