app_home:
    path:     /
    defaults:
        _controller: TrailWarehouseAppBundle:Home:index

app_home_contact:
    path:     /nous-contacter
    defaults:
        _controller: TrailWarehouseAppBundle:Home:contact

app_home_about:
    path:     /a-propos-de-trailwarehouse
    defaults:
        _controller: TrailWarehouseAppBundle:Home:about

app_home_mentions:
    path:     /mentions-legales
    defaults:
        _controller: TrailWarehouseAppBundle:Home:mentions
