imports:
    - { resource: config.yml }

parameters :
    # knp_snappy
    wkhtmltopdf   : '%base_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
    wkhtmltoimage : '%base_dir%/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64'

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
