easy_admin :

    site_name : '<span>TW&nbsp;Admin</span>'

    design :
        brand_color : 'hsl(165, 65%%, 40%%)'
        color_scheme : 'dark'
        form_theme :
            - 'easy_admin/form/bootstrap_3_layout.html.twig'
        assets :
            favicon :
                path : 'images/feet.png'
                mime_type : 'image/png'
            css :
                - 'css/admin.css'
        menu :
            - label : ""
            - { entity : 'Brand', icon : 'bold' }
            - label : "____________________"
            - { entity : 'Category', icon : 'th-large' }
            - label : "____________________"
            - label : "Production"
              icon : gears
              children :
                  - { entity : 'Family', icon : 'book' }
                  - { entity : 'Product', icon : 'leaf' }
            - label : "____________________"
            - label : "Détails"
              icon : th-list
              children :
                  - { entity : 'Size', icon : 'image' }
                  - { entity : 'Color', icon : 'paint-brush' }
                  - { entity : 'FamilyColor', icon : 'image' }
            - label : "____________________"
            - label : "Membres"
              icon : "users"
              children :
                  - { entity : 'User', icon : 'user' }
                  - { entity : 'Role', icon : 'shield' }
                  - { entity : 'Address', icon : 'address-card' }
            - label : "____________________"
            - label : "Facturation"
              icon : money
              children :
                  - { entity : 'Order', icon : 'tablet' }
                  - { entity : 'Vat', icon : 'percent' }
                  - { entity : 'Promo', icon : 'barcode' }
            - label : "____________________"
            - { entity : 'Review', icon : 'sticky-note' }
            - label : "____________________"
            - { label : 'Retour au site', icon : 'hand-o-left', route : 'app_home' }

    list :
        title : 'Liste des %%entity_label%%'
        max_results : 20
        actions :
            - { name : 'new', icon : 'plus', label : 'Ajouter' }
            - { name : 'show', icon : 'eye', label : '' }
            - { name : 'edit', icon : 'pencil', label : '' }
            - { name : 'delete', icon : 'trash', label : '' }
            - { name : 'search', icon : 'search', label : 'Rechercher' }

    show :
        title : '%%entity_label%% (#%%entity_id%%)'
        max_results : 20
        actions :
            - { name : 'edit', icon : 'pencil', css_class : 'btn btn-primary', label : 'Modifier' }
            - { name : 'delete', icon : 'trash', css_class : 'btn btn-danger', label : 'Supprimer' }
            - { name : 'list', icon : 'hand-o-left', css_class : 'btn btn-blue', label : 'Retour' }

    edit :
        title   : 'Modification : ID #%%entity_id%%'
        actions :
            - { name : 'delete', icon : 'trash', css_class : 'btn btn-danger', label : 'Supprimer' }
            - { name : 'show', icon : 'eye', css_class : 'btn btn-blue', label : 'Voir' }
            - { name : 'new', icon : 'plus', css_class : 'btn btn-blue', label : 'Nouveau' }
            - { name : 'list', icon : 'hand-o-left', css_class : 'btn btn-blue', label : 'Retour' }

    new :
        title   : "Création d'un nouvel élément"
        actions :
            - { name : 'list', icon : 'hand-o-left', css_class : 'btn btn-blue', label : 'Retour' }

    formats :
        datetime : 'Y, M, j @ H:i:s'


    entities :
        User      :
            class      : TrailWarehouse\AppBundle\Entity\User
            controller : TrailWarehouse\AppBundle\Controller\Admin\UserController
            label      : 'Utilisateurs'
            help       : 'Rôles disponibles : <em class="txt-secondary">ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN</em>'
            list       :
                fields :
                    - id
                    - { property : 'fullname', label : "Nom complet", type : 'string' }
                    - { property : 'email', label : "E-mail", type : 'email' }
                    - { property : 'role', label : 'Profil', type : 'association' }
                    - { property : 'isActive', label : 'active', type : 'toggle' }
            show       :
                fields :
                    - id
                    - { property : 'firstname', label : "Prénom", type : 'string' }
                    - { property : 'lastname', label : "Nom d'usage", type : 'string' }
                    - { property : 'email', label : "E-mail", type : 'email' }
                    - { property : 'password', label : "Mot de passe crypté", type : 'string' }
                    - { property : 'role', label : 'Profil', type : 'association' }
                    - { property : 'isActive', label : 'active', type : 'toggle' }
            form  :
                fields :
                    - { type: 'group', css_class: 'col-sm-6', label: 'Identité' }
                    - { property : 'lastname', label : "Nom d'usage", type : 'text' }
                    - { property : 'firstname', label : 'Prénom', type : 'text' }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Identifiants' }
                    - { property : 'email', label : 'Email', type : 'email' }
                    - { property : 'plainPassword', label : 'Mot de passe', type : 'password', type_options : { required : false } }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Autres informations' }
                    - { property : 'role', label : 'Profil', type_options : { expanded : true } }
                    - { type : 'divider' }
                    - { property : 'isActive', label : 'Actif' }
            edit  :
                title : "Modification de l'utilisateur #%%entity_id%%"
            new   :
                title : "Création d'un nouvel utilisateur"

        Role      :
            class : TrailWarehouse\AppBundle\Entity\Role
            label : 'Rôles'
            form :
                fields :
                    - { property : 'name', label : 'Nom' }
            edit :
                title : 'Modification du rôle #%%entity_id%%'
            new :
                title : "Création d'un rôle"

        Address      :
            class : TrailWarehouse\AppBundle\Entity\Address
            label : 'Addresses'
            list :
                fields :
                    - id
                    - { property : 'street', label : 'N°, Voie' }
                    - { property : 'zipcode', label : 'Code postal' }
                    - { property : 'city', label : 'Ville' }
                    - { property : 'user', label : 'Utilisateur' }
            show :
                fields :
                    - id
                    - { property : 'street', label : 'N°, Voie' }
                    - { property : 'zipcode', label : 'Code postal' }
                    - { property : 'city', label : 'Ville' }
                    - { property : 'user', label : 'Utilisateur' }
            form :
                fields :
                    - { property : 'user', label : 'Utilisateur' }
                    - { property : 'street', label : 'N°, Voie' }
                    - { property : 'zipcode', label : 'Code postal' }
                    - { property : 'city', label : 'Ville' }
            edit :
                title : "Modification de l'adresse #%%entity_id%%"
            new :
                title : "Création d'une adresse"

        Brand     :
            class : TrailWarehouse\AppBundle\Entity\Brand
            label : 'Marques'
            list :
                fields :
                  - id
                  - { property : 'name', label : 'Nom', type : 'string' }
                  - { property : 'imageName', label : 'Logo', type : 'image', base_path : '%vich_uploader.mappings.brand_image%' }
            show :
                fields :
                  - id
                  - { property : 'name', label : 'Nom', type : 'string' }
                  - { property : 'imageName', label : 'Logo', type : 'image', base_path : '%vich_uploader.mappings.brand_image%' }
                  - { property : 'slug', label : 'Slug', type : 'string' }
            form :
                fields :
                  - { property : 'name', label : 'Nom' }
                  - { property : 'imageFile', label : 'Logo (max : 2Mo)', type : 'vich_image', base_path : '%vich_uploader.mappings.brand_image%' }
            edit :
                title : "Modification de la marque #%%entity_id%%"
            new  :
                title : "Création d'une marque"

        Category  :
            class : TrailWarehouse\AppBundle\Entity\Category
            label : 'Catégories'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom' }
            show :
                fields :
                    - id
                    - { property : 'name', label : 'Nom' }
                    - { property : 'slug', label : 'Slug' }
            form :
                fields :
                    - { property : 'name', label : 'Nom' }
            edit :
                title : "Modification de la catégorie #%%entity_id%%"
            new  :
                title : "Création d'une catégorie"

        Family    :
            class : TrailWarehouse\AppBundle\Entity\Family
            label : 'Familles'
            list :
                help : "Cliquer sur 'Voir/Modifier' pour visualiser/éditer la description d'une famille"
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'brand', label : 'Marque', type : 'association' }
                    - { property : 'category', label : 'Catégorie', type : 'association' }
                    - { property : 'products', label : 'Produits' }
                    - { property : 'visuels', label : 'Visuels' }
                    - { property : 'reviews', label : 'Notes' }
            form :
                fields :
                    - { property : 'brand', label : 'Marque' }
                    - { property : 'category', label : 'Catégorie' }
                    - { property : 'name', label : 'Nom' }
                    - { property : 'description', label : 'Description' }
            edit :
                title : "Modification de la famille %%entity_id%%"
            new  :
                title : "Création d'une famille"

        FamilyColor    :
            class : TrailWarehouse\AppBundle\Entity\FamilyColor
            label : 'Visuels'
            list :
                fields :
                    - id
                    - { property : 'family', label : 'Famille' }
                    - { property : 'color', label : 'Couleur' }
                    - { property : 'imageName', label : 'Visuel (max : 2Mo)', type : 'image', base_path : '%vich_uploader.mappings.family_color_image%' }
            show :
                title : "Visuel #%%entity_id%%"
                fields :
                    - id
                    - { property : 'family', label : 'Famille' }
                    - { property : 'color', label : 'Couleur' }
                    - { property : 'imageName', label : 'Visuel (max : 2Mo)', type : 'image', base_path : '%vich_uploader.mappings.family_color_image%' }
            form :
                fields :
                  - { property : 'family', label : 'Famille' }
                  - { property : 'color', label : 'Couleur' }
                  - { property : 'imageFile', label : 'Visuel (max : 2Mo)', type : 'vich_image', base_path : '%vich_uploader.mappings.family_color_image%' }
            edit :
                title : "Modification du visuel #%%entity_id%%"
            new  :
                title : "Création d'un visuel"

        Product   :
            class      : TrailWarehouse\AppBundle\Entity\Product
            controller : TrailWarehouse\AppBundle\Controller\Admin\ProductController
            label      : 'Produits'
            list       :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'family', label : 'Famille', type : 'association' }
                    - { property : 'color', label : 'Couleur', type : 'association' }
                    - { property : 'size', label : 'Taille', type : 'association' }
                    - { property : 'stock', label : 'Stock', type : 'integer' }
                    - { property : 'price', label : 'Prix', format: '%.2f €'  }
            form  :
                fields :
                    - { property : 'name', label : 'Nom', help : 'Généré automatiquement si laissé vide', type_options : { required : false } }
                    - { property : 'family', label : 'Famille' }
                    - { property : 'color', label : 'Couleur' }
                    - { property : 'size', label : 'Taille' }
                    - { property : 'stock', label : 'Stock' }
                    - { property : 'price', label : 'Prix', type : 'money', type_options : { currency : 'EUR' } }
            edit :
                title : "Modification du produit #%%entity_id%%"
            new  :
                title : "Création d'un produit"

        Color     :
            class : TrailWarehouse\AppBundle\Entity\Color
            label : 'Couleurs'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom' }
                    - { property : 'value', label : 'Valeur' }
                    - { property : 'echantillon', label : 'Echantillon' }
            form :
                fields :
                    - { property : 'name', label : 'Nom' }
                    - { property : 'value', label : 'Valeur' }
            edit :
                title : "Modification de la couleur #%%entity_id%%"
            new  :
                title : "Création d'une couleur"

        Size      :
            class : TrailWarehouse\AppBundle\Entity\Size
            label : 'Tailles'
            list :
                fields :
                    - id
                    - { property : 'value', label : 'Valeur', type : 'string' }
                    - { property : 'unit', label : 'Unité', type : 'string' }
            show :
                fields :
                    - id
                    - { property : 'value', label : 'Valeur' }
                    - { property : 'unit', label : 'Unité' }
                    - { property : 'unitShortcut', label : 'Raccourci unité' }
            form :
                fields :
                    - { property : 'value', label : 'Valeur' }
                    - { property : 'unit', label : 'Unité' }
                    - { property : 'unitShortcut', label : 'Raccourci unité' }
            edit :
                title : "Modification de la taille #%%entity_id%%"
            new  :
                title : "Création d'une taille"

        Order     :
            class : TrailWarehouse\AppBundle\Entity\Order
            label : 'Commandes'
            disabled_actions :
                - 'edit'
            list :
                fields :
                    - id
                    - { property : 'user', label : 'Client' }
                    - { property : 'creationDate', label : "Date création" }
                    - { property : 'sendingDate', label : "Date d'envoi" }
                    - { property : 'deliveryDate', label : "Date de livraison" }
                    - { property : 'total', label : "Total", format: '%.2f €' }
            show :
                fields :
                    - id
                    - { property : 'user', label : 'Client' }
                    - { property : 'coordinate', label : "Addrese de livraison" }
                    - { property : 'creationDate', label : "Date création" }
                    - { property : 'sendingDate', label : "Date d'envoi" }
                    - { property : 'deliveryDate', label : "Date de livraison" }
                    - { property : 'total', label : "Total", format: '%.2f €' }

        Promo     :
            class : TrailWarehouse\AppBundle\Entity\Promo
            label : 'Codes promo'
            list :
                fields :
                    - id
                    - { property : 'code', label : 'Code', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'float' }
                    - { property : 'isNew', label : 'Nouveau', type : 'boolean' }
                    - { property : 'isActive', label : 'Actif', type : 'boolean' }
                    - { property : 'isExpired', label : 'Expiré', type : 'boolean' }
                    - { property : 'start', label : 'Début', type : 'datetime' }
                    - { property : 'end', label : 'Fin', type : 'datetime' }
            show :
                fields :
                    - id
                    - { property : 'code', label : 'Code' }
                    - { property : 'value', label : 'Valeur' }
                    - { property : 'isNew', label : 'Nouveau', type : boolean }
                    - { property : 'isActive', label : 'Actif', type : boolean }
                    - { property : 'isExpired', label : 'Expiré', type : boolean }
                    - { property : 'start', label : 'Début' }
                    - { property : 'end', label : 'Fin' }
            form :
                fields :
                    - { property : 'code', label : 'Code' }
                    - { property : 'value', label : 'Valeur' }
                    - { property : 'start', label : 'Début', type : 'datetime' }
                    - { property : 'end', label : 'Fin', type : 'datetime' }
            edit :
                title : "Modification du code promo #%%entity_id%%"
            new  :
                title : "Création d'un code promo"

        Review    :
            class : TrailWarehouse\AppBundle\Entity\Review
            label : 'Avis'
            help : 'Cliquez sur "Voir" pour accéder au commentaire associé'
            disabled_actions : ['edit', 'new']
            list :
                fields :
                    - id
                    - { property : 'family', label : "Famille" }
                    - { property : 'rating', label : "Note", format : "%u / 5" }
                    - { property : 'creationDate', label : "Date du commentaire" }
            show :
                fields :
                    - id
                    - { property : 'family', label : "Famille" }
                    - { property : 'rating', label : "Note", format : "%u / 5" }
                    - { property : 'commentary', label : "Commentaire" }
                    - { property : 'creationDate', label : "Date du commentaire" }

        Vat       :
            class : TrailWarehouse\AppBundle\Entity\Vat
            label : 'TVA'
            list :
                fields :
                    - id
                    - { property : 'country', label : 'Pays', type : 'string' }
                    - { property : 'value', label : 'Valeur', format : '%.2f' }
            show :
                fields :
                    - id
                    - { property : 'country', label : 'Pays', type : 'string' }
                    - { property : 'value', label : 'Valeur', format : '%.2f' }
            form :
                fields :
                    - { property : 'country', label : 'Pays', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'percent' }
            edit :
                title : "Modification de la TVA #%%entity_id%%"
            new  :
                title : "Création d'une TVA"
