easy_admin :

    site_name : '<em style="font-size:1.8rem;">Trail&nbsp;Warehouse&nbsp;Admin</em>'

    design :
        brand_color : 'hsl(348, 65%, 50%)'
        color_scheme : 'dark'
        form_theme :
            - 'easy_admin/form/bootstrap_3_layout.html.twig'
        assets :
            favicon :
                path : 'images/feet.png'
                mime_type : 'image/png'
            css :
                - 'css/admin.css'

    list         :
        title    : 'Liste des %%entity_label%%'
        actions  :
            - { name : 'new', icon : 'plus', label : 'Ajouter' }
            - { name : 'show', icon : '', label : 'Voir' }
            - { name : 'edit', icon : '', label : 'Modifier' }
            - { name : 'delete', icon : '', label : 'Supprimer' }
            - { name : 'search', icon : 'search', label : 'Rechercher' }

    show         :
        title    : '%%entity_label%% (#%%entity_id%%)'

    edit         :
        title    : '%%entity_label%% (#%%entity_id%%)'

    formats      :
        datetime : 'Y, M, j @ H:i:s'

    entities :
        User      :
            class      : TrailWarehouse\AppBundle\Entity\User
            controller : TrailWarehouse\AppBundle\Controller\Admin\UserController
            label      : 'Utilisateurs'
            help       : 'Rôles disponibles : <em class="txt-secondary">ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN</em>'
            list       :
                fields :
                    - id
                    - { property : 'fullname', label : "Nom complet", type : 'string' }
                    - { property : 'role', label : 'Profil', type : 'association' }
                    - { property : 'isActive', label : 'active', type : 'toggle' }
            edit  :
                fields :
                    - { type: 'group', css_class: 'col-sm-6', label: 'Identité' }
                    - { property : 'lastname', label : "Nom d'usage", type : 'text' }
                    - { property : 'firstname', label : 'Prénom', type : 'text' }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Identifiants' }
                    - { property : 'email', label : 'Email', type : 'email' }
                    - { property : 'plainPassword', label : 'Mot de passe', type : 'password', type_options : { required : false } }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Autres informations' }
                    - { property : 'role', label : 'Profil', type_options : { expanded : true } }
                    - { property : 'isActive', label : 'Actif' }
            new   :
                fields :
                    - { type: 'group', css_class: 'col-sm-6', label: 'Identité' }
                    - { property : 'lastname', label : "Nom d'usage", type : 'text' }
                    - { property : 'firstname', label : 'Prénom', type : 'text' }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Identifiants' }
                    - { property : 'email', label : 'Email', type : 'email' }
                    - { property : 'plainPassword', label : 'Mot de passe', type : 'password', type_options : { required : true } }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Autres informations' }
                    - { property : 'role', label : 'Profil', type : 'entity', type_options : { expanded : true, class : 'TrailWarehouse\AppBundle\Entity\Role' } }
                    - { property : 'isActive', label : 'Actif' }

        Role      :
            class : TrailWarehouse\AppBundle\Entity\Role
            label : 'Rôles'
            edit :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'text' }

        Brand     :
            class : TrailWarehouse\AppBundle\Entity\Brand
            label : 'Marques'
            image_base_path : '%web_url%'
            list :
                fields :
                  - id
                  - { property : 'name', label : 'Nom', type : 'string' }
                  - { property : 'logo', label : 'Logo', type : 'image' }
                  - { property : 'slug', label : 'Slug', type : 'string' }
            edit :
                fields :
                  - { property : 'name', label : 'Nom' }
                  - { property : 'logo', label : 'Logo', type : 'file' }

        Category  :
            class : TrailWarehouse\AppBundle\Entity\Category
            label : 'Catégories'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }

        Family    :
            class : TrailWarehouse\AppBundle\Entity\Family
            label : 'Familles'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'brand', label : 'Marque', type : 'association' }
                    - { property : 'category', label : 'Catégorie', type : 'association' }
                    - { property : 'products', label : 'Produits' }
                    - { property : 'colors', label : 'Visuels' }
                    - { property : 'reviews', label : 'Notes' }
        Product   :
            class      : TrailWarehouse\AppBundle\Entity\Product
            controller : TrailWarehouse\AppBundle\Controller\Admin\ProductController
            label      : 'Produits'
            list       :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'family', label : 'Famille', type : 'association' }
                    - { property : 'color', label : 'Couleur', type : 'association' }
                    - { property : 'size', label : 'Taille', type : 'association' }
                    - { property : 'stock', label : 'Stock', type : 'integer' }
                    - { property : 'price', label : 'Prix', type : 'float', format : '%.2f' }
            edit  :
                fields :
                    - { property : 'name', label : 'Nom', help : 'Généré automatiquement si laissé vide', type_options : { required : false } }
                    - { property : 'family', label : 'Famille' }
                    - { property : 'color', label : 'Couleur' }
                    - { property : 'size', label : 'Taille' }
                    - { property : 'stock', label : 'Stock' }
                    - { property : 'price', label : 'Prix' }
            new   :
                fields :
                    - { property : 'name', label : 'Nom' }
                    - { property : 'family', label : 'Famille' }
                    - { property : 'color', label : 'Couleur' }
                    - { property : 'size', label : 'Taille' }
                    - { property : 'price', label : 'Prix', type : 'number', format : '%.2f' }
                    - { property : 'stock', label : 'Stock' }

        Color     :
            class : TrailWarehouse\AppBundle\Entity\Color
            label : 'Couleurs'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'string' }
                    - { property : 'echantillon', label : 'Echantillon', type : 'string' }
        Size      :
            class : TrailWarehouse\AppBundle\Entity\Size
            label : 'Tailles'
            list :
                fields :
                    - id
                    - { property : 'value', label : 'Valeur', type : 'string' }
                    - { property : 'unit', label : 'Unité', type : 'string' }
                    - { property : 'unitShortcut', label : 'Raccourci', type : 'string' }
        Order     :
            class : TrailWarehouse\AppBundle\Entity\Order
            label : 'Commandes'
            disabled_actions :
                - 'edit'
        Promo     :
            class : TrailWarehouse\AppBundle\Entity\Promo
            label : 'Codes promo'
            list :
                fields :
                    - id
                    - { property : 'code', label : 'Code', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'float' }
                    - { property : 'isNew', label : 'Nouveau', type : 'boolean' }
                    - { property : 'isActive', label : 'Actif', type : 'boolean' }
                    - { property : 'isExpired', label : 'Expiré', type : 'boolean' }
                    - { property : 'start', label : 'Début', type : 'datetime' }
                    - { property : 'end', label : 'Fin', type : 'datetime' }
        Review    :
            class : TrailWarehouse\AppBundle\Entity\Review
            label : 'Avis'
        Vat       :
            class : TrailWarehouse\AppBundle\Entity\Vat
            label : 'Taux'
            list :
                fields :
                    - id
                    - { property : 'country', label : 'Pays', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'float' }
        Image     :
            class : TrailWarehouse\AppBundle\Entity\Image
            label : 'Images'
