easy_admin :

    site_name : '<em style="font-size:1.8rem;">Trail&nbsp;Warehouse&nbsp;Admin</em>'

    design :
        brand_color : 'hsl(348, 65%, 50%)'
        color_scheme : 'dark'
        assets :
            favicon :
                path : 'images/feet.png'
                mime_type : 'image/png'
            css :
                - 'css/admin.css'

    list         :
        title    : 'Liste des %%entity_label%%'
    show         :
        title    : '%%entity_label%% (#%%entity_id%%)'
    formats      :
        datetime : 'Y, M, j @ H:i:s'

    entities :
        User      :
            class : TrailWarehouse\AppBundle\Entity\User
            label : 'Utilisateurs'
            help  : 'Rôles disponibles : <em class="txt-secondary">ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN</em>'
        Brand     :
            class : TrailWarehouse\AppBundle\Entity\Brand
            label : 'Marques'
            list :
              fields :
                - id
                - { property : 'name', label : 'Nom', type : 'string' }
        Category  :
            class : TrailWarehouse\AppBundle\Entity\Category
            label : 'Catégories'
            list :
              fields :
                - id
                - { property : 'name', label : 'Nom', type : 'string' }
        Family    :
            class : TrailWarehouse\AppBundle\Entity\Family
            label : 'Familles'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'brand', label : 'Marque', type : 'association' }
                    - { property : 'category', label : 'Catégorie', type : 'association' }
                    - { property : 'products', label : 'Produits' }
                    - { property : 'colors', label : 'Visuels' }
                    - { property : 'reviews', label : 'Notes' }
        Product   :
            class : TrailWarehouse\AppBundle\Entity\Product
            label : 'Produits'
            list :
              fields :
                - id
                - { property : 'name', label : 'Nom', type : 'string' }
                - { property : 'family', label : 'Famille', type : 'association' }
                - { property : 'color', label : 'Couleur', type : 'association' }
                - { property : 'size', label : 'Taille', type : 'association' }
                - { property : 'stock', label : 'Stock', type : 'integer' }
                - { property : 'price', label : 'Prix', type : 'float', format : '%.2f' }
        Color     :
            class : TrailWarehouse\AppBundle\Entity\Color
            label : 'Couleurs'
            list :
              fields :
                - id
                - { property : 'name', label : 'Nom', type : 'string' }
                - { property : 'value', label : 'Valeur', type : 'string' }
                - { property : 'echantillon', label : 'Echantillon', type : 'string' }
        Size      :
            class : TrailWarehouse\AppBundle\Entity\Size
            label : 'Tailles'
            list :
              fields :
                - id
                - { property : 'value', label : 'Valeur', type : 'string' }
                - { property : 'unit', label : 'Unité', type : 'string' }
                - { property : 'unitShortcut', label : 'Raccourci', type : 'string' }
        Order     :
            class : TrailWarehouse\AppBundle\Entity\Order
            label : 'Commandes'
        Promo     :
            class : TrailWarehouse\AppBundle\Entity\Promo
            label : 'Codes promo'
            list :
                fields :
                    - id
                    - { property : 'code', label : 'Code', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'float' }
                    - { property : 'isNew', label : 'Nouveau', type : 'boolean' }
                    - { property : 'isActive', label : 'Actif', type : 'boolean' }
                    - { property : 'isExpired', label : 'Expiré', type : 'boolean' }
                    - { property : 'start', label : 'Début', type : 'datetime' }
                    - { property : 'end', label : 'Fin', type : 'datetime' }
        Review    :
            class : TrailWarehouse\AppBundle\Entity\Review
            label : 'Avis'
        Vat       :
            class : TrailWarehouse\AppBundle\Entity\Vat
            label : 'Taux'
            list :
                fields :
                    - id
                    - { property : 'country', label : 'Pays', type : 'string' }
                    - { property : 'value', label : 'Valeur', type : 'float' }
        Image     :
            class : TrailWarehouse\AppBundle\Entity\Image
            label : 'Images'
