easy_admin_bundle:
    resource: "@TrailWarehouseAppBundle/Controller/Admin/BackendController.php"
    type:     annotation
    prefix:   /admin

trail_warehouse_app:
    resource: "@TrailWarehouseAppBundle/Resources/config/routing.yml"
    prefix:   /

user_app:
    path                 : /user/init
    defaults             :
        _controller      : TrailWarehouseAppBundle:User:init
