my_route:
    path: /bla/foo/{param1}/{param2}
    defaults:
        _controller: TrailWarehouseAppBundle:Home:test
    requirements:
        _method  : GET

easy_admin_bundle:
    resource : "@TrailWarehouseAppBundle/Controller/Admin/BackendController.php"
    type     : annotation
    prefix   : /admin

# easy_admin_bundle :
#     resource : "@EasyAdminBundle/Controller/AdminController.php"
#     type     : annotation
#     prefix   : /admin

trail_warehouse_test:
    resource : "@TrailWarehouseAppBundle/Controller/TestController.php"
    type     : annotation
    prefix   : /test

# trail_warehouse_annotation:
#     resource : "@TrailWarehouseAppBundle/Controller"
#     type     : annotation

trail_warehouse_app:
    resource : "@TrailWarehouseAppBundle/Resources/config/routing.yml"
    prefix   : /

user_app:
    path            : /user/init
    defaults        :
        _controller : TrailWarehouseAppBundle:User:init
