easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    
trail_warehouse_app:
    resource: "@TrailWarehouseAppBundle/Resources/config/routing.yml"
    prefix:   /
