trail_warehouse_admin:
    resource: "@TrailWarehouseAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

trail_warehouse_app:
    resource: "@TrailWarehouseAppBundle/Resources/config/routing.yml"
    prefix:   /
