# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders :
        Symfony\Component\Security\Core\User\User :
            algorithm : bcrypt
        TrailWarehouse\AppBundle\Entity\User :
            algorithm : bcrypt

    role_hierarchy :
        ROLE_ADMIN       : ROLE_USER
        ROLE_SUPER_ADMIN : [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers :
        in_memory :
            memory :
                users :
                    toto@toto.fr :
                        password : '$2y$13$naOK2oxxFahRPNXb0hTzYegBztL9IHZ/xR1Ftx67YGH2tepBFadAy'
                        roles    : 'ROLE_SUPER_ADMIN'

        db_trailwarehouse :
            entity        :
                class     : TrailWarehouseAppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev :
            pattern   : ^/(_(profiler|wdt)|css|images|js)/
            security  : false
        # Main Firewall
        main :
            pattern   : ^/
            anonymous : ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic :
            #     provider :  db_trailwarehouse

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login :
                provider   : db_trailwarehouse
                login_path : app_signin
                check_path : app_signin

            # remember_me :
            #     secret : '%secret%'

            logout :
                path   : app_signout
                target : app_shop

    access_control :
        - { path: ^/admin/add, roles : ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles : ROLE_ADMIN }
        - { path: ^/espace-perso, roles : ROLE_USER }
        - { path: ^/deconnexion, roles : ROLE_USER }
