# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders :
        Symfony\Component\Security\Core\User\User:
            algorithm : bcrypt

    role_hierarchy :
        ROLE_ADMIN       : ROLE_USER
        ROLE_SUPER_ADMIN : [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers :
        in_memory :
            memory :
                users :
                    user  :
                        password : $2y$13$0Qlf/QiYFUStkojucAWrKORvQPR4jqZ.Dym2WCDxsi1co4VkRSzIO
                        roles    : 'ROLE_USER'
                    admin :
                        password : $2y$13$Mk3Qncp.P5RKtax0oXDrLOLO3CRqWZtfi5RZUrj5hTmBmOzqJk1vW
                        roles    : 'ROLE_ADMIN'
                    mickael :
                        password : $2y$13$bLhahJ0foR90DYez16T1m.UQH5ioaMcrX9nPAe.XDaE.rVY9FuJve
                        roles    : 'ROLE_SUPER_ADMIN'
        db_trailwarehouse :
            entity :
                class    : TrailWarehouseAppBundle:Member

    provider : in_memory

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev :
            pattern   : ^/(_(profiler|wdt)|css|images|js)/
            security  : false
        # Main Firewall
        main :
            pattern : ^/
            anonymous : ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic :
                provider : in_memory

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login :
               provider   : db_trailwarehouse
               login_path : app_client_signin
               check_path : app_client_signin

            logout :
                path : app_client_signout
                target : app_shop

    access_control :
        - { path: ^/admin, roles: ROLE_ADMIN }
