# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders :
        Symfony\Component\Security\Core\User\User :
            algorithm : bcrypt
        TrailWarehouse\AppBundle\Entity\User :
            algorithm : bcrypt

    role_hierarchy :
        ROLE_ADMIN       : ROLE_USER
        ROLE_SUPER_ADMIN : [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers :

        db_trailwarehouse :
            entity        :
                class     : TrailWarehouseAppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev :
            pattern   : ^/(_(profiler|wdt)|css|images|js)/
            security  : false
        # Main Firewall
        main :
            pattern   : ^/
            anonymous : true
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login :
                provider   : db_trailwarehouse
                login_path : app_signin
                check_path : app_signin
                username_parameter : trailwarehouse_appbundle_user[email]
                password_parameter : trailwarehouse_appbundle_user[password]

            # remember_me :
            #     secret : '%secret%'

            logout :
                path   : app_signout
                target : app_shop

    access_control :
        - { path: ^/admin/add, roles      : ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles          : ROLE_ADMIN }
        - { path: ^/connexion, roles      : IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles    : IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/deconnexion, roles    : IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/espace-perso, roles   : ROLE_USER }
        - { path: ^/panier/valider, roles : ROLE_USER }
