parameters :
    vich_uploader.mappings.brand_image  : '%prefix%/images/brands'
    vich_uploader.mappings.family_color_image : '%prefix%/images/families'

vich_uploader :
    db_driver : orm

    mappings :

        brand_image            :
            uri_prefix         : '%vich_uploader.mappings.brand_image%'
            upload_destination : '%images_dir%/brands'
            namer              :
                service : vich_uploader.namer_origname
            inject_on_load   : true
            delete_on_update : true
            delete_on_remove : true

        family_color_image     :
            uri_prefix         : '%vich_uploader.mappings.family_color_image%'
            upload_destination : '%images_dir%/families'
            namer :
                service : vich_uploader.namer_origname
