# /commande

app_order         :
  path            : /
  defaults        :
    _controller   : TrailWarehouseAppBundle:Order:index

app_order_coordinates :
  path            : /coordonnees
  defaults        :
    _controller   : TrailWarehouseAppBundle:Order:coordinates

app_order_payment :
  path            : /paiement
  defaults        :
    _controller   : TrailWarehouseAppBundle:Order:payment

app_order_create  :
  path            : /creation
  defaults        :
    _controller   : TrailWarehouseAppBundle:Order:create
