vich_uploader :

    mappings :

        family_color_image     :
            uri_prefix         : '%vich_uploader.mappings.family_color_image%'
            upload_destination : '%images_dir%/families'
            namer :
                service : vich_uploader.namer_origname
            inject_on_load   : false
            delete_on_update : true
            delete_on_remove : true
