app_signup:
    path:     /inscription
    defaults:
        _controller: TrailWarehouseAppBundle:User:signup

app_signin:
    path:     /connexion
    defaults:
        _controller: TrailWarehouseAppBundle:User:signin

app_signin_check:
    path:     /verification

app_signout:
    path:     /deconnexion

app_account:
    path:     /espace-perso
    defaults:
        _controller: TrailWarehouseAppBundle:User:account

app_shop_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/Shop/routing.yml"
    prefix:   /boutique

app_api_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/Api/routing.yml"
    prefix:   /api

app_admin_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/Admin/routing.yml"
    prefix:   /admin

app_home_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/Home/routing.yml"
    prefix:   /
