app_home_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/routing_home.yml"
    prefix:   /

app_shop_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/routing_shop.yml"
    prefix:   /boutique

app_client_root:
    resource: "@TrailWarehouseAppBundle/Resources/config/routing_client.yml"
    prefix:   /client
