app_shop:
    path:     /
    defaults:
        _controller: TrailWarehouseAppBundle:Shop:index

app_shop_category:
    path:     /categorie-{category}
    defaults:
        _controller: TrailWarehouseAppBundle:Shop:category

app_shop_family:
    path:     /fiche-produit/{family}
    defaults:
        _controller: TrailWarehouseAppBundle:Shop:family

app_shop_error:
    path:     /{slug}
    defaults:
        _controller: TrailWarehouseAppBundle:Error:index
