# /

app_signup :
    path:     /inscription
    methods: 'GET'
    defaults:
        _controller: TrailWarehouseAppBundle:User:signup

app_signup_post :
    path:     /inscription
    methods: 'POST'
    defaults:
        _controller: TrailWarehouseAppBundle:User:signupProcess

app_signin :
    path:     /connexion
    defaults:
        _controller: TrailWarehouseAppBundle:User:signin

app_signout :
    path:     /deconnexion

app_account_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Account/routing.yml"
    prefix   : /espace-perso

app_shop_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Shop/routing.yml"
    prefix   : /boutique

app_cart_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Cart/routing.yml"
    prefix   : /panier

app_order_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Order/routing.yml"
    prefix   : /commande

app_api_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Api/routing.yml"
    prefix   : /api

app_admin_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Admin/routing.yml"
    prefix   : /admin

app_contact :
    resource : "@TrailWarehouseAppBundle/Resources/config/Contact/routing.yml"
    prefix   : /contact

app_home_root :
    resource : "@TrailWarehouseAppBundle/Resources/config/Home/routing.yml"
    prefix   : /