services:
#    app.example:
#        class: TrailWarehouse\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    trail_warehouse.restocker:
        alias: TrailWarehouse/AppBundle/Service/Restocker
        public: true
