easy_admin :
    entities :
        Product :
            class      : TrailWarehouse\AppBundle\Entity\Product
            controller : TrailWarehouse\AppBundle\Controller\Admin\ProductController
            label      : 'Produits'
            list :
                fields :
                    - id
                    - { property : 'name', label : 'Nom', type : 'string' }
                    - { property : 'family', label : 'Famille', type : 'association' }
                    - { property : 'color', label : 'Couleur', type : 'association' }
                    - { property : 'size', label : 'Taille', type : 'association' }
                    - { property : 'stock', label : 'Stock', type : 'integer' }
                    - { property : 'price', label : 'Prix', format: '%.2f €'  }
                actions :
                    - { name : 'restock', icon : plus-square }
            form  :
                fields :
                    - { property : 'name', label : 'Nom', help : 'Généré automatiquement si laissé vide', type_options : { required : false } }
                    - { property : 'family', label : 'Famille' }
                    - { property : 'color', label : 'Couleur' }
                    - { property : 'size', label : 'Taille' }
                    - { property : 'stock', label : 'Stock' }
                    - { property : 'price', label : 'Prix', type : 'money', type_options : { currency : 'EUR' } }
            edit :
                title : "Modification du produit #%%entity_id%%"
            new  :
                title : "Création d'un produit"
