app_admin :
    path                 : /
    defaults             :
        _controller      : TrailWarehouseAppBundle:Admin/Test:add

app_admin_test :
    path                 : /add
    methods              : [GET]
    defaults             :
        _controller      : TrailWarehouseAppBundle:Admin/Test:add
