services:
    _defaults :
        autowire      : true
        autoconfigure : true
        public        : false

    trail_warehouse.restock_listener:
        class: TrailWarehouse\AppBundle\EventListener\RestockListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        public: true
