services:
    _defaults :
        autowire      : true
        autoconfigure : true
        public        : false

    trail_warehouse.restock_listener:
        class: TrailWarehouse\AppBundle\EventListener\RestockListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    trail_warehouse.interactive_login_listener:
        class: TrailWarehouse\AppBundle\EventListener\InteractiveLoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
