# src > TrailWarehouse > AdminBundle > Resources > config > routing.yml

admin_home_root:
    resource: "@TrailWarehouseAdminBundle/Resources/config/routing_home.yml"
    prefix:   /

admin_member_root:
    resource: "@TrailWarehouseAdminBundle/Resources/config/routing_member.yml"
    prefix:   /member

admin_category_root:
    resource: "@TrailWarehouseAdminBundle/Resources/config/routing_category.yml"
    prefix:   /category

admin_family_root:
    resource: "@TrailWarehouseAdminBundle/Resources/config/routing_family.yml"
    prefix:   /family

admin_product_root:
    resource: "@TrailWarehouseAdminBundle/Resources/config/routing_product.yml"
    prefix:   /product
