category_create:
    path:     /category/create
    defaults:
        _controller: TrailWarehouseAdminBundle:Category:create

category_read:
    path:     /category/read/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Category:read
    requirements:
        id: '\d+'

category_update:
    path:     /category/update/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Category:update
    requirements:
        id: '\d+'

category_delete:
    path:     /category/delete/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Category:delete
    requirements:
        id: '\d+'
