# src > TrailWarehouse > AdminBundle > Resources > config > routing_product.yml

admin_product:
    path:     /
    defaults:
        _controller: TrailWarehouseAdminBundle:Product:index

admin_product_create:
    path:     /create
    defaults:
        _controller: TrailWarehouseAdminBundle:Product:create

admin_product_read:
    path:     /read/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Product:read
    requirements:
        id: '\d+'

admin_product_update:
    path:     /update/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Product:update
    requirements:
        id: '\d+'

admin_product_delete:
    path:     /delete/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Product:delete
    requirements:
        id: '\d+'
