# src > TrailWarehouse > AdminBundle > Resources > config > routing_member.yml

admin_member:
    path:     /
    defaults:
        _controller: TrailWarehouseAdminBundle:Member:index

admin_member_create:
    path:     /create
    defaults:
        _controller: TrailWarehouseAdminBundle:Member:create

admin_member_read:
    path:     /read/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Member:read
    requirements:
        id: '\d+'

admin_member_update:
    path:     /update/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Member:update
    requirements:
        id: '\d+'

admin_member_delete:
    path:     /delete/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Member:delete
    requirements:
        id: '\d+'
