# src > TrailWarehouse > AdminBundle > Resources > config > routing_family.yml

admin_family:
    path:     /
    defaults:
        _controller: TrailWarehouseAdminBundle:Family:index

admin_family_create:
    path:     /create
    defaults:
        _controller: TrailWarehouseAdminBundle:Family:create

admin_family_read:
    path:     /read/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Family:read
    requirements:
        id: '\d+'

admin_family_update:
    path:     /update/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Family:update
    requirements:
        id: '\d+'

admin_family_delete:
    path:     /delete/{id}
    defaults:
        _controller: TrailWarehouseAdminBundle:Family:delete
    requirements:
        id: '\d+'
